language: elixir
elixir:
    - 1.3.2
notifications:
  recipients:
    - drew@kerrigan.io
otp_release:
  - 19.0
env:
  - MIX_ENV=test
services:
  - riak
script: mix test --exclude riak2 --exclude riakts
